In [55]:
# importing all libraryes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
# Read Data set
data=pd.read_csv('D:\github-d\AI-ML\Datasets\Heart.csv')
print(data)

     Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0  

In [57]:
data['ChestPain']= data['ChestPain'].astype('category')
data['ChestPain']=data['ChestPain'].cat.codes
data['ChestPain']


0      3
1      0
2      0
3      1
4      2
      ..
298    3
299    0
300    0
301    2
302    1
Name: ChestPain, Length: 303, dtype: int8

In [58]:
data['Thal']= data['Thal'].astype('category')
data['Thal']=data['Thal'].cat.codes
data['Thal']

data['AHD']= data['AHD'].astype('category')
data['AHD']=data['AHD'].cat.codes
data['AHD']

0      0
1      1
2      1
3      0
4      0
      ..
298    1
299    1
300    1
301    1
302    0
Name: AHD, Length: 303, dtype: int8

In [59]:
# Know about Null values
data.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          0
AHD           0
dtype: int64

In [60]:
# clear the Null values
data=data.dropna()

In [61]:
# Seperate the data as X and y
X=data.drop(['AHD'],axis=1).values
y=data['AHD'].values
X.shape

(299, 14)

In [62]:
# Now it is the time to split the x data as Train and Test Data
X

array([[  1.,  63.,   1., ...,   3.,   0.,   0.],
       [  2.,  67.,   1., ...,   2.,   3.,   1.],
       [  3.,  67.,   1., ...,   2.,   2.,   2.],
       ...,
       [300.,  68.,   1., ...,   2.,   2.,   2.],
       [301.,  57.,   1., ...,   2.,   1.,   2.],
       [302.,  57.,   0., ...,   2.,   1.,   1.]])

In [63]:
# Split x as Train and test data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=21)
xtrain,ytrain

(array([[291.,  67.,   1., ...,   2.,   0.,   2.],
        [265.,  61.,   1., ...,   2.,   1.,   1.],
        [198.,  45.,   0., ...,   2.,   0.,   1.],
        ...,
        [ 49.,  65.,   0., ...,   1.,   1.,   1.],
        [263.,  60.,   0., ...,   1.,   0.,   1.],
        [210.,  62.,   0., ...,   2.,   0.,   1.]]),
 array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0,

In [64]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
sd=StandardScaler()
xtrain_sc=sd.fit_transform(xtrain)
xtest_sc=sd.fit_transform(xtest)
xtest_sc,xtest_sc

(array([[-1.11146419, -0.9102049 , -1.3462912 , ...,  1.97949865,
         -0.75727937, -0.52692446],
        [ 1.64572583,  0.29126557,  0.74278135, ...,  0.531085  ,
          0.3245483 ,  1.10835835],
        [-1.18068235, -0.0364082 ,  0.74278135, ...,  0.531085  ,
          0.3245483 ,  1.10835835],
        ...,
        [ 0.6189898 , -1.7840016 ,  0.74278135, ...,  0.531085  ,
         -0.75727937,  1.10835835],
        [ 0.87278972,  2.14808356, -1.3462912 , ..., -0.91732864,
          0.3245483 , -0.52692446],
        [ 0.69974432,  1.05583768, -1.3462912 , ...,  0.531085  ,
          1.40637597, -0.52692446]]),
 array([[-1.11146419, -0.9102049 , -1.3462912 , ...,  1.97949865,
         -0.75727937, -0.52692446],
        [ 1.64572583,  0.29126557,  0.74278135, ...,  0.531085  ,
          0.3245483 ,  1.10835835],
        [-1.18068235, -0.0364082 ,  0.74278135, ...,  0.531085  ,
          0.3245483 ,  1.10835835],
        ...,
        [ 0.6189898 , -1.7840016 ,  0.74278135, ...,  

In [65]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(random_state=0)
lg.fit(xtrain_sc,ytrain)


LogisticRegression(random_state=0)

In [66]:
yhat=lg.predict(xtrain_sc)
yhat

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int8)

In [67]:
lg.score(xtrain_sc,ytrain)



0.8660287081339713

In [68]:
from sklearn.metrics import r2_score
r2_score(ytrain,yhat)

0.45864939870490296

In [69]:
lg.score(xtest_sc,ytest)

0.8333333333333334